ALL = sudoku1 sudoku2 sudoku3 sudoku4 sudoku5 sudoku6 sudoku7 sudoku8

all: $(ALL)

clean:
	rm -f a.out *.o $(ALL)


sudoku1: sudoku1.cpp
	g++ -std=c++98 -o sudoku1 sudoku1.cpp 

sudoku2: sudoku2.cpp
	g++ -std=c++98 -o sudoku2 sudoku2.cpp 

sudoku3: sudoku3.cpp
	g++ -std=c++98 -o sudoku3 sudoku3.cpp 

sudoku4: sudoku4.cpp
	g++ -std=c++98 -o sudoku4 sudoku4.cpp 

sudoku5: sudoku5.cpp
	g++ -std=c++98 -o sudoku5 sudoku5.cpp 

sudoku6: sudoku6.cpp
	g++ -std=c++98 -o sudoku6 sudoku6.cpp 

sudoku7: sudoku7.cpp
	g++ -std=c++98 -o sudoku7 sudoku7.cpp 

sudoku8: sudoku8.cpp
	g++ -std=c++98 -o sudoku8 sudoku8.cpp 

