ALL = keno-ll keno-ll2 keno-ll3 keno-ll4 keno-ll5

all: $(ALL) 

clean:
	rm -f a.out $(ALL)



keno-ll: keno-ll.cpp
	g++ -O3 -o keno-ll keno-ll.cpp

keno-ll2: keno-ll2.cpp
	g++ -O3 -o keno-ll2 keno-ll2.cpp

keno-ll3: keno-ll3.cpp
	g++ -O3 -o keno-ll3 keno-ll3.cpp

keno-ll4: keno-ll4.cpp
	g++ -O3 -o keno-ll4 keno-ll4.cpp

keno-ll5: keno-ll5.cpp
	g++ -O3 -o keno-ll5 keno-ll5.cpp
