ALL = bin/keno-ll bin/keno-ll2 bin/keno-ll3 bin/keno-ll4 bin/keno-ll5

all: $(ALL) 

clean:
	rm -f a.out $(ALL)

bin/keno-ll: src/keno-ll.cpp
	g++ -O3 -o bin/keno-ll src/keno-ll.cpp

bin/keno-ll2: src/keno-ll2.cpp
	g++ -O3 -o bin/keno-ll2 src/keno-ll2.cpp

bin/keno-ll3: src/keno-ll3.cpp
	g++ -O3 -o bin/keno-ll3 src/keno-ll3.cpp

bin/keno-ll4: src/keno-ll4.cpp
	g++ -O3 -o bin/keno-ll4 src/keno-ll4.cpp

bin/keno-ll5: src/keno-ll5.cpp
	g++ -O3 -o bin/keno-ll5 src/keno-ll5.cpp
