All = balls-in-boxes-1 \
      balls-in-boxes-2 \
      balls-in-boxes-3 \
      balls-in-boxes-4 \
      balls-in-boxes-5 \
      gen-3-teams \
      divmod \
      gen-permutations \
      gen-teams \
      SimpleRotationDecoder 

all: $(All)

clean:
	rm -f $(All)

balls-in-boxes-1: balls-in-boxes-1.cpp
	g++ -o balls-in-boxes-1 balls-in-boxes-1.cpp

balls-in-boxes-2: balls-in-boxes-2.cpp
	g++ -o balls-in-boxes-2 balls-in-boxes-2.cpp

balls-in-boxes-3: balls-in-boxes-3.cpp
	g++ -o balls-in-boxes-3 balls-in-boxes-3.cpp

balls-in-boxes-4: balls-in-boxes-4.cpp
	g++ -o balls-in-boxes-4 balls-in-boxes-4.cpp

balls-in-boxes-5: balls-in-boxes-5.cpp
	g++ -o balls-in-boxes-5 balls-in-boxes-5.cpp

gen-3-teams: gen-3-teams.cpp
	g++ -o gen-3-teams gen-3-teams.cpp

divmod: divmod.cpp
	g++ -o divmod divmod.cpp

gen-permutations: gen-permutations.cpp
	g++ -o gen-permutations gen-permutations.cpp

gen-teams: gen-teams.cpp
	g++ -o gen-teams gen-teams.cpp

SimpleRotationDecoder: SimpleRotationDecoder.cpp
	g++ -o SimpleRotationDecoder SimpleRotationDecoder.cpp

